### ISSUE TITLE
Rails 3.1.8

### ISSUE THREAD

**Issue by masak2009** [markets/unscoped_associations#12]
Hey Markets,
Maybe I am doing something wrong but it seems to not work with rail 3.1.8.

My question is simple. Is this part of code has to work with your gem?

class Article < ActiveRecord::Base
  belongs_to :user, :unscoped => true
end

class User << ActiveRecord::Base
  has_many :articles
  default_scope where("users.invisible != ?",true)
end

On Rails console running:
Article.find(1).user

This will return nil if user.invisible = true

Any advice? I lost one day and can not solve this....

**Comment by markets** [comment]
Hi @masak2009,

Yes, it has to work this way. All tests are passing in last Rails 3 stable (3.2.X). I'll try to run tests in 3.1 and I'll ping you. Thanks for reporting!

**Comment by markets** [comment]
Hey @masak2009,

I just pushed a branch running tests with Rails (ActiveRecord) 3.1: https://github.com/markets/unscoped_associations/tree/rails31. And you're right, it does not work: https://travis-ci.org/markets/unscoped_associations/builds/76759738, specs against 3.1 are not passing.

Btw, Rails 3.1 is officialy unmaintained (even security issues), so I recommend to move, at least, to 3.2-stable... 

That said, if you want to work on a patch for this, I'd be really happy to review/merge it :+1: 

Otherwise, I'll modify dependencies/docs and require AR 3.2 at minimum.

Keep in touch. Thanks.

**Comment by masak2009** [comment]
Hey @markets 
at first sorry for a late answer.
I resolve the issue directly in my project which finally works without this gem. So you should only change dependencies.

Yes, the best solution is upgrade rails but for large commercial project is not easy to do it because it should break something and it will take a lot of hours to get it work again :-/
