### ISSUE TITLE
.count does not skip the default scope

### ISSUE THREAD

**Issue by encoder** [markets/unscoped_associations#13]
I am using rails 4.2.3 and unscoped_associations 0.6.5.

Although the gem works when fetching associated records, it doesn't seem to work when _counting_ associated records.

I'm using different models than your example, but the behavior in your example would be something like this: `user.all_comments.count` returns a smaller number than `user.all_comments.to_a.count`. Per SQL debugging in the rails console, the default scope is not skipped when .count is added.

**Comment by markets** [comment]
Hi @encoder,

Yes, I think you're right, it probably doesn't work. This plugin is based on the [unscoped](http://api.rubyonrails.org/classes/ActiveRecord/Scoping/Default/ClassMethods.html#method-i-unscoped) method, I remember that chaining new scopes after unscoped calls are broken in AR itself. I'll take a look in deeper. 

Using `to_a` works because all objects are already fetched from database and you are calling `count` over an array. 

I'm not sure if this is easy to fix, need to review some AR internals... If you want to take a look would be really helpful.

Thanks for reporting.

**Comment by markets** [comment]
Hi @encoder, I added some notes about this in the docs: https://github.com/markets/unscoped_associations#notes.
