### ISSUE TITLE
Broken inverse_of

### ISSUE THREAD

**Issue by MmKolodziej** [markets/unscoped_associations#15]
Adding unscoped to association seems to break inverse_of and caching of parent model instances.

``` ruby
class RedemptionOffer < ActiveRecord::Base
  has_one :voucher_template, inverse_of: :redemption_offer, dependent: :destroy
  acts_as_paranoid
end
```

``` ruby
class VoucherTemplate < ActiveRecord::Base
  belongs_to :redemption_offer, inverse_of: :voucher_template#, unscoped: true
  acts_as_paranoid
end
```

``` ruby
jruby-1.7.24 :033 > r = RedemptionOffer.new
jruby-1.7.24 :034 > r.build_voucher_template
jruby-1.7.24 :035 > r.voucher_template.redemption_offer.class
 => RedemptionOffer(columns)
```

After uncommenting the `#unscoped: true` from VoucherTemplate model:

``` ruby
jruby-1.7.24 :033 > r = RedemptionOffer.new
jruby-1.7.24 :034 > r.build_voucher_template
jruby-1.7.24 :035 > r.voucher_template.redemption_offer.class
 => NilClass 
```

Tested on Rails 3.2.21. I might try to fix that later if I'll find the time. Overall nice gem, 10/10 would use again

**Comment by markets** [comment]
Hi @MmKolodziej, thanks for that!

I really didn't use the `inverse_of` option in the apps I have with this gem, so I never found this crash 😅 . There are no tests related, so yes, it can probably break something. To be honest, this part of Rails itself is kind of "fragile" and obscure, or at least for me. They made some related changes, since Rails 4, to allow to use blocks on associations, but last time I tried, didn't work fully ...

I'll try to take a deeper look asap and see if I can make some patch to fix this case. If you finally got some time to work on it, would be really helpful.

About the caching problem, I think it's also related to https://github.com/markets/unscoped_associations/pull/14.

Thanks!

**Comment by markets** [comment]
Hi @MmKolodziej, did you manage to find some time to take a look? I just pushed a new version (0.7.0) with some caching stuff to avoid fetch from DB on each "getter" call and some code clean up. Let me know if this version works for your case!
