### ISSUE TITLE
Deprication warning in Rails 5.0.0.1

### ISSUE THREAD

**Issue by rahulv2** [markets/unscoped_associations#18]
I got this warning after using `usncoped: true` in a `has_may` `belongs_to association`:

 `DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super. (called from <top (required)> at /home/rhl/myapp/config/application.rb:8)
DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super. (called from <top (required)> at /home/rhl/myapp/config/application.rb:8)
DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super. (called from <top (required)> at /home/rhl/myapp/config/application.rb:8)
`

**Comment by markets** [comment]
Hi @rahulv2, yes it's a known warning on Rails 5, but the code still works, just raises those deprecation warnings. 

Rails core team deprecated the `alias_method_chain` and will be probably removed on next minor release (Rails 5.1). That's why this plugin will not work on Rails 5.1, see more: #16. 

Thanks!
