### ISSUE TITLE
alias_method_chain is deprectated

### ISSUE THREAD

**Issue by edwardmp** [markets/unscoped_associations#19]
`DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super.`

I'll see If I can submit a pull request for this.

**Comment by markets** [comment]
Hi @edwardmp, sorry for the delay :)

See:
- https://github.com/markets/unscoped_associations/issues/16
- https://github.com/markets/unscoped_associations/issues/18

I'm not planning to support Rails 5.1.

On the other hand, I would not like to drop support for older Rubies, because I actually use this gem in a "legacy" Rails 3 app with Ruby 1.9.3, and as noted in the Readme, this plugin was originally thought and built for a Rails 3.2 application. Rails 4.X and Rails 5.0 are supported, but more for easy migrations. I recommend to use AR internals (associations with scope blocks + unscope...) for new apps.

**Comment by markets** [comment]
Hi @edwardmp, I'm going to close this issue (and the attached PR) as per my previous comment, due to inactivity and complexity to deal with AR internals (they change a lot on each major version). For new apps in Rails 5.1+, I recommend to use associations with scope blocks or the unscope method to accomplish similar functionality, as noted in the readme and gemspec:

    spec.add_dependency "activerecord", ">= 3.2.0", "< 5.1.0"

Thanks! Hope some day we have this fully fixed on Rails itself, to be honest I'm not sure what's the status of unscoped assoc + preloading on newer Rails, but seems hard to fix  :sweat_smile:

PS. I see you also commented here https://github.com/rails/rails/issues/11036#issuecomment-285417910 :smile:
