### ISSUE TITLE
Stack level too deep

### ISSUE THREAD

**Issue by albertodega** [markets/unscoped_associations#8]
Hi guys,
I'm having the following problem:
I've a couple of classes structured like follows:
```ruby
class FilmOccupation < ActiveRecord::Base
  belongs_to :theater, unscoped: true #works great with nothing or unscoped: false
end

class Theater < ActiveRecord::Base
  has_many :film_occupations # same with unscoped: true/false
  default_scope { where(active: true) }
end
```

I'm on ruby 2.1, Rails 3.2.21, and launching the following command:
```ruby
FilmOccupation.last.theater
```
or anything launching the belongs_to associations, with or without archived theaters i alway get a load of
```sql
[...]
  Theater Load (0.4ms)  SELECT "theaters".* FROM "theaters" WHERE "theaters"."id" IN (8)
  Theater Load (0.6ms)  SELECT "theaters".* FROM "theaters" WHERE "theaters"."id" IN (8)
  Theater Load (0.6ms)  SELECT "theaters".* FROM "theaters" WHERE "theaters"."id" IN (8)
[...]
```
ending with
```
SystemStackError: stack level too deep
```

Suggestions?

**Comment by markets** [comment]
Hi @albertodega,

I can't reproduce your error, tests are passing locally and on CI and they run similar calls in different places. Recently, I pushed a branch impriving the CI: running platform against different AR versions. You can see the ouput here: https://travis-ci.org/markets/unscoped_associations/builds/62528117, all tests are passing with different combinations Ruby-Rails, including your setup (2.1, 3.2).

Seems really weird, could be caused by other gems, or a combination of them?

So, is this repo open-source? I'll take a look. If not, could you please share more relevant code, in order to reproduce the error.

Thanks.

**Comment by albertodega** [comment]
hei @markets!
Unfortunately the repo is private.
Well, in the end i've extended the second class overriding the defualt scope so i have disabled the gem at the moment.
That said, for what you are telling me i'm pretty sure that the error is due to another gem.
I plan to retry with your gem soon, having to integrate more scopes. I'll keep you up to date as soon as i will retry on, maybe, different classes and models.
If you want you can momentarily close this issue.
Thank you!
Alberto

**Comment by markets** [comment]
Hi @albertodega, yes it's probably caused by another plugins...

Please, reopen or ping me with any kind of new report related to this gem.

Thank you!
